# Generated by Django 5.1.4 on 2025-02-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='physical_activity_level',
            field=models.CharField(blank=True, choices=[('Sedentary', 'Sedentary'), ('Active', 'Active'), ('Very Active', 'Very Active')], max_length=50, null=True),
        ),
    ]
